### ISSUE TITLE
For other languages: path to bootstrap-datepicker-js in Booking.php is wrong

### ISSUE THREAD

**Issue by git-gnulf** [tastyigniter/ti-ext-reservation#18]
**Expected behavior:**
If changing the system-language the calendar has to change to the locale specifications (name of month and days, and so on)

**Actual behavior:**
If changing the system-language the calendar stays with its english settings

**Reproduce steps:**
- create your own de-language
- switch to the new language in system properties (and maybe the logged in user, too) 
- go to the link reservation and book a table 

Have a look at your browsers developer console-log: You will find an error that a script could not loaded:
https://my-restaurant.com/vendor/datepicker/bootstrap-datepicker/locales/bootstrap-datepicker.de.min.js

Have a look at your file system. The correct location of the script is:
https://my-restaurant.com/app/admin/formwidgets/datepicker/assets/vendor/datepicker/locales/bootstrap-datepicker.de.min.js

**Version:**
3.0.4

**Additional Information:**
In file Booking.php in components
at line 133:
if (setting('default_language') != 'en')
            $this->addJs('~/app/admin/formwidgets/datepicker/assets/vendor/datepicker/locales/bootstrap-datepicker.'.strtolower(str_replace('_', '-', setting('default_language'))).'.min.js', 'bootstrap-datepicker-js');

**Comment by sampoyigi** [comment]
Fixed. Thanks!

**Comment by elmarra90** [comment]
$this->addJs('~/app/admin/formwidgets/datepicker/assets/vendor/datepicker/bootstrap-datepicker/locales/bootstrap-datepicker.'.strtolower(str_replace('_', '-', setting('default_language'))).'.min.js', 'bootstrap-datepicker-js');
the path is incorrect, it contains a duplicate folder .. the correct path is this, but I don't know how to fix it

  $this->addJs('~/app/admin/formwidgets/datepicker/assets/vendor/datepicker/locales/bootstrap-datepicker.'.strtolower(str_replace('_', '-', setting('default_language'))).'.min.js', 'bootstrap-datepicker-js');

**Comment by elmarra90** [comment]
> Fixed. Thanks!

$this->addJs('~/app/admin/formwidgets/datepicker/assets/vendor/datepicker/bootstrap-datepicker/locales/bootstrap-datepicker.'.strtolower(str_replace('_', '-', setting('default_language'))).'.min.js', 'bootstrap-datepicker-js');
the path is incorrect, it contains a duplicate folder .. the correct path is this, but I don't know how to fix it

$this->addJs('~/app/admin/formwidgets/datepicker/assets/vendor/datepicker/locales/bootstrap-datepicker.'.strtolower(str_replace('_', '-', setting('default_language'))).'.min.js', 'bootstrap-datepicker-js');

**Comment by git-gnulf** [comment]
> $this->addJs('~/app/admin/formwidgets/datepicker/assets/vendor/datepicker/bootstrap-datepicker/locales/bootstrap-datepicker.'.strtolower(str_replace('_', '-', setting('default_language'))).'.min.js', 'bootstrap-datepicker-js');
> the path is incorrect, it contains a duplicate folder .. the correct path is this, but I don't know how to fix it

Yes, this path better than before but is still wrong. The part '/bootstrap-datepicker' is too much.

How to fix?
Go to filesystem and edit: 
/extensions/igniter/reservation/components/Booking.php
goto line 133
There you can change the path.

**Comment by elmarra90** [comment]
Yes for the front office lanto I solved.
But in the administration panel, in reservations there is the same problem of the wrong path .. you have to solve them too
my-restourant.com/admin/reservations/create
